aqf:
    resource: "@AQFBundle/Resources/config/routing.yml"
    prefix:   /mission

# app/config/routing.yml
welcome:
    path:     /
    defaults: { _controller: AppBundle:Default:index }

login:
    path: /login
    defaults: { _controller: AppBundle:Default:index }
