# app/config/routing.yml

aqf:
    resource: "@AQFBundle/Resources/config/routing.yml"
    prefix:   /

welcome:
    path:     /
    defaults: { _controller: AppBundle:Default:index }

login:
    path: /login
    methods: [POST]
    defaults: { _controller: AppBundle:Default:login }

logout:
    path:     /logout
    methods: [GET]
    defaults: { _controller: AppBundle:Default:logout }
