aqf_homepage:
    path:     /mission
    methods: [GET]
    defaults: { _controller: AQFBundle:Default:index }

aqf_addedit:
    path:     /aqf_addedit/{mid}
    methods: [GET, POST]
    defaults: { _controller: AQFBundle:Default:addedit }

# aqf_save:
#     path:     /aqf_save/
#     methods: [POST]
#     defaults: { _controller: AQFBundle:Default:save }
